global:
  data_folder: "/home/mu/workspace/roboracer/data/kine_rand_uniform/"
  # data_folder: "/home/mu/workspace/roboracer/data/rand_validation/"
  model_folder: "/home/mu/workspace/roboracer/src/gp-ws/models/"
  eval_folder: "/home/mu/workspace/roboracer/src/gp-ws/evaluate_out/"
  log_folder: "/home/mu/workspace/roboracer/src/gp-ws/logs/"

compare_config:
  if_norm: True
  c: 3000
  train_test_split: 0.8
  epoch: 300
  learning_rate: 0.1
  
gp_train:
  if_norm: false 
  train_test_split: 0.8
  epoch: 50
  model:
    type: 2
    learning_rate: 0.1
    inducing: 500
    independent: true

gp_eval:
  model_dir: "/home/mu/workspace/roboracer/src/gp-ws/models/sparse/20250627_175029/"
  model_type: 1
  if_norm: false
  eval_type: 0

eval_sim:
  model_dir: "/home/mu/workspace/roboracer/src/gp-ws/models/sparse/20250627_154019/"
  model_type: 1
  if_norm: True