global:
  data_folder: "/home/mu/workspace/roboracer/data/kine_rand_uniform/"
  # data_folder: "/home/mu/workspace/roboracer/data/rand_validation/"
  model_folder: "/home/mu/workspace/roboracer/src/gp-ws/models/"
  eval_folder: "/home/mu/workspace/roboracer/src/gp-ws/evaluate_out/"
  log_folder: "/home/mu/workspace/roboracer/src/gp-ws/logs/"

compare_config:
  if_norm: True
  c: 3000
  train_test_split: 0.8
  epoch: 100
  learning_rate: 0.1
  
gp_train:
  model_type: 1
  if_norm: True 
  train_test_split: 0.8
  epoch: 100
  learning_rate: 0.1

gp_eval:
  model_dir: "/home/mu/workspace/roboracer/src/gp-ws/models/sparse/20250622_214332/"
  model_type: 1
  if_norm: True
  eval_type: 1