global:
  data_folder: "/home/mu/workspace/roboracer/data/kine_rand_uniform/"
  # data_folder: "/home/mu/workspace/roboracer/data/rand_validation/"
  model_folder: "/home/mu/workspace/roboracer/src/gp-ws/models/"
  eval_folder: "/home/mu/workspace/roboracer/src/gp-ws/evaluate_out/"
  log_folder: "/home/mu/workspace/roboracer/src/gp-ws/logs/"

compare_config:
  if_norm: True
  N_sub: 3000
  train_test_split: 0.5
  epoch: 100
  
gp_train:
  model_type: 1
  if_norm: True 
  train_test_split: 0.8
  epoch: 10
  learning_rate: 0.01

gp_eval:
  model_name: ""
  model_type: 1
  if_norm: True