# Configure the path
global_config:
  data_folder: "data/kine_rand_uniform/"
  # data_folder: "data/rand_validation/"
  model_folder: "src/gp-ws/models/"
  eval_folder: "src/gp-ws/evaluate_out/"
  log_folder: "src/gp-ws/logs/"

# Not used in current version, for `gpdyn_baseline.py`, might have bugs
compare_config:
  if_norm: True
  c: 3000
  train_test_split: 0.8
  epoch: 500
  learning_rate: 0.1
  
gp_train:
  if_norm: true             # If true, normalize the data
  train_test_split: 0.8
  epoch: 30                 
  model:
    type: 1                 # 0: Exact GP 1: Sparse GP, 2: SV GP   
    learning_rate: 0.01 
    inducing: 1000        
    independent: true       # If true, use independent GP for each output
    batch_size: 256      

# Not used in current version, for `gpdyn_eval_eu.py`, might have bugs
gp_eval:
  model_dir: "src/gp-ws/models/sparse/20250702_190840/"
  model_type: 1
  if_norm: true
  eval_type: 0

# Not used
eval_sim:
  model_dir: "src/gp-ws/models/sparse/20250627_154019/"
  model_type: 1
  if_norm: True